import { Product } from './types';

export const SAMPLE_PRODUCTS: Product[] = [
    // ===== ขนม / ของกินเล่น =====
    {
        id: 'p1',
        barcode: 'SNK-001',
        name: 'ตะวันลาบแซ่บ',
        category: 'ขนม',
        stock_quantity: 8,
        unit: 'แพ็ค',
        image_url: '🌶️',
        tracking_mode: 'quantity',
    },
    {
        id: 'p2',
        barcode: 'SNK-002',
        name: 'ดิวเบอร์รี่ บลูเบอร์รี่ (6 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 12,
        unit: 'แพ็ค',
        image_url: '🫐',
        tracking_mode: 'quantity',
    },
    {
        id: 'p3',
        barcode: 'SNK-003',
        name: 'ดิวเบอร์รี่ สตรอว์เบอร์รี่ (6 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 12,
        unit: 'แพ็ค',
        image_url: '🍓',
        tracking_mode: 'quantity',
    },
    {
        id: 'p4',
        barcode: 'SNK-004',
        name: 'ปี๊บสับปะรด',
        category: 'ขนม',
        stock_quantity: 6,
        unit: 'ปี๊บ',
        image_url: '🍍',
        tracking_mode: 'usage',
        usage_count: 0,
        status: 'available',
    },
    {
        id: 'p5',
        barcode: 'SNK-005',
        name: 'ขาไก่',
        category: 'ขนม',
        stock_quantity: 6,
        unit: 'ห่อ',
        image_url: '🍗',
        tracking_mode: 'quantity',
    },
    {
        id: 'p6',
        barcode: 'SNK-006',
        name: 'สติ๊กช็อกโกแลต',
        category: 'ขนม',
        stock_quantity: 6,
        unit: 'ห่อ',
        image_url: '🍫',
        tracking_mode: 'quantity',
    },
    {
        id: 'p7',
        barcode: 'SNK-007',
        name: 'โอรีโอ้ (24 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 24,
        unit: 'แพ็ค',
        image_url: '🍪',
        tracking_mode: 'quantity',
    },
    {
        id: 'p8',
        barcode: 'SNK-008',
        name: 'ดาโกะ สติ๊ก รสชีส (27 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 2,
        unit: 'แพ็ค',
        image_url: '🧀',
        tracking_mode: 'quantity',
    },
    {
        id: 'p9',
        barcode: 'SNK-009',
        name: 'ดาโกะ สติ๊ก รสสตรอว์เบอร์รี่ (27 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 2,
        unit: 'แพ็ค',
        image_url: '🍬',
        tracking_mode: 'quantity',
    },
    {
        id: 'p10',
        barcode: 'SNK-010',
        name: 'ซันไบทส์ (12 ชิ้น)',
        category: 'ขนม',
        stock_quantity: 10,
        unit: 'แพ็ค',
        image_url: '🥨',
        tracking_mode: 'quantity',
    },
    {
        id: 'p11',
        barcode: 'SNK-011',
        name: 'น้ำพริก',
        category: 'ขนม',
        stock_quantity: 8,
        unit: 'แพ็ค',
        image_url: '🫙',
        tracking_mode: 'quantity',
    },

    // ===== อาหาร / บะหมี่กึ่งสำเร็จรูป =====
    {
        id: 'p12',
        barcode: 'FD-001',
        name: 'ควิก รสต้มโค้ง (30 ซอง)',
        category: 'อาหาร',
        stock_quantity: 1,
        unit: 'แพ็ค',
        image_url: '🍜',
        tracking_mode: 'quantity',
    },
    {
        id: 'p13',
        barcode: 'FD-002',
        name: 'ไวไว รสหอยลาย (30 ซอง)',
        category: 'อาหาร',
        stock_quantity: 1,
        unit: 'แพ็ค',
        image_url: '🍜',
        tracking_mode: 'quantity',
    },
    {
        id: 'p14',
        barcode: 'FD-003',
        name: 'ไวไว รสหมูสับต้มยำ (30 ซอง)',
        category: 'อาหาร',
        stock_quantity: 1,
        unit: 'แพ็ค',
        image_url: '🍜',
        tracking_mode: 'quantity',
    },
    {
        id: 'p15',
        barcode: 'FD-004',
        name: 'ไวไว รสออริจินัล (30 ซอง)',
        category: 'อาหาร',
        stock_quantity: 1,
        unit: 'แพ็ค',
        image_url: '🍜',
        tracking_mode: 'quantity',
    },
    {
        id: 'p16',
        barcode: 'FD-005',
        name: 'ไวไว รสต้มยำ (30 ซอง)',
        category: 'อาหาร',
        stock_quantity: 1,
        unit: 'แพ็ค',
        image_url: '🍜',
        tracking_mode: 'quantity',
    },
    {
        id: 'p17',
        barcode: 'FD-006',
        name: 'โจ๊กคัพ รสหมูสาหร่าย (4 ถ้วย)',
        category: 'อาหาร',
        stock_quantity: 24,
        unit: 'แพ็ค',
        image_url: '🥣',
        tracking_mode: 'quantity',
    },
    {
        id: 'p18',
        barcode: 'FD-007',
        name: 'ปลากระป๋องซูเปอร์ฟิช (10 กระป๋อง)',
        category: 'อาหาร',
        stock_quantity: 20,
        unit: 'แพ็ค',
        image_url: '🐟',
        tracking_mode: 'quantity',
    },

    // ===== เครื่องดื่ม =====
    {
        id: 'p19',
        barcode: 'BEV-001',
        name: 'นมสตรอว์เบอร์รี่ (6 กล่อง)',
        category: 'เครื่องดื่ม',
        stock_quantity: 10,
        unit: 'แพ็ค',
        image_url: '🥛',
        tracking_mode: 'quantity',
    },
    {
        id: 'p20',
        barcode: 'BEV-002',
        name: 'นมองุ่น (6 กล่อง)',
        category: 'เครื่องดื่ม',
        stock_quantity: 10,
        unit: 'แพ็ค',
        image_url: '🍇',
        tracking_mode: 'quantity',
    },

    // ===== ของสด =====
    {
        id: 'p21',
        barcode: 'FRS-001',
        name: 'ไข่ (แผงละ 30 ฟอง)',
        category: 'ของสด',
        stock_quantity: 3,
        unit: 'แผง',
        image_url: '🥚',
        tracking_mode: 'quantity',
    },
    {
        id: 'p22',
        barcode: 'FRS-002',
        name: 'ไส้กรอกแดง',
        category: 'ของสด',
        stock_quantity: 3.5,
        unit: 'กก.',
        image_url: '🌭',
        tracking_mode: 'quantity',
    },
    {
        id: 'p23',
        barcode: 'FRS-003',
        name: 'ไส้กรอกไก่',
        category: 'ของสด',
        stock_quantity: 3,
        unit: 'กก.',
        image_url: '🌭',
        tracking_mode: 'quantity',
    },
    {
        id: 'p24',
        barcode: 'FRS-004',
        name: 'ลูกชิ้นเนื้อ',
        category: 'ของสด',
        stock_quantity: 1,
        unit: 'กก.',
        image_url: '🧆',
        tracking_mode: 'quantity',
    },
    {
        id: 'p25',
        barcode: 'FRS-005',
        name: 'ลูกชิ้นหมู',
        category: 'ของสด',
        stock_quantity: 2,
        unit: 'กก.',
        image_url: '🧆',
        tracking_mode: 'quantity',
    },
];
